name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies & CI tools
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Lint code with flake8
        run: flake8 ingestion spark_jobs
      - name: Run tests with pytest
        run: pytest
      - name: Create .env file for Docker Compose
        run: |
          echo "YOUTUBE_API_KEY=dummy_key" > .env
          echo "POSTGRES_USER=user" >> .env
          echo "POSTGRES_PASSWORD=password" >> .env
          echo "POSTGRES_DB=db" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=admin@example.com" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=admin" >> .env
      - name: Build Docker images
        run: docker-compose build
